#!/usr/bin/env python3
"""Share-a-Clicky local connector: MCP over stdio, Python 3.8+, no dependencies.

Add to HeyClicky: Settings > Integrations > Add custom connector >
Advanced > Command on this Mac.
  Command:   python3 (or a full path such as /opt/anaconda3/bin/python3)
  Arguments: /full/path/to/share_a_clicky_mcp.py

Reads clickys.json (generated by build.py) from the same folder.
Logging is off by default. To debug, set the environment variable
SHARE_A_CLICKY_LOG=/full/path/connector.log in HeyClicky's connector settings.
Note that HeyClicky sends turn metadata with each tool call, and the log records it.
"""
import atexit
import datetime
import json
import os
import signal
import sys
import traceback

SERVER_NAME = "share-a-clicky"
SERVER_VERSION = "0.1.0"
SUPPORTED_PROTOCOL_VERSIONS = ["2025-06-18", "2025-03-26", "2024-11-05"]  # newest first
HERE = os.path.dirname(os.path.abspath(__file__))
DATA_PATH = os.path.join(HERE, "clickys.json")
MAX_LOG_BYTES = 512 * 1024
MAX_MESSAGE_BYTES = 64 * 1024  # same cap as the Worker
# Models often type Unicode dashes (e.g. U+2011) inside ids like "follow-up-keeper".
DASH_LIKE_CHARACTERS = "\u2010\u2011\u2012\u2013\u2014\u2015\u2212"

def log_path():
    configured = os.environ.get("SHARE_A_CLICKY_LOG", "").strip()
    if not configured or configured.lower() == "off":
        return None
    return configured


def log(event, payload):
    path = log_path()
    if not path:
        return
    try:
        if os.path.exists(path) and os.path.getsize(path) > MAX_LOG_BYTES:
            os.replace(path, path + ".old")
        with open(path, "a", encoding="utf-8") as log_file:
            stamp = datetime.datetime.now().isoformat(timespec="seconds")
            log_file.write(f"{stamp} pid={os.getpid()} {event} {json.dumps(payload)[:2000]}\n")
    except (OSError, TypeError, ValueError):
        pass


def load_data(path=None):
    with open(path or DATA_PATH) as data_file:
        return json.load(data_file)


def normalize_slug(raw_value):
    text = str(raw_value or "").strip().lower()
    for separator in (" ", "_") + tuple(DASH_LIKE_CHARACTERS):
        text = text.replace(separator, "-")
    while "--" in text:
        text = text.replace("--", "-")
    return text.strip("-")


def find_clicky(data, raw_value):
    wanted = normalize_slug(raw_value)
    if not wanted:
        return None
    for clicky in data["clickys"]:
        if wanted in (clicky["slug"], normalize_slug(clicky["name"])):
            return clicky
    return None


MAX_SAFE_ID = 2 ** 53 - 1  # the Worker runs in JavaScript; larger ids would lose precision there


def valid_request_id(value):
    """MCP request ids are strings or integers, never null."""
    if isinstance(value, str):
        return True
    return isinstance(value, int) and not isinstance(value, bool) and abs(value) <= MAX_SAFE_ID


def reject_constant(name):
    raise ValueError(f"{name} is not valid JSON")


MAX_NESTING = 64  # MCP messages are shallow; the Worker applies the same limit


def nesting_depth(value):
    deepest, stack = 0, [(value, 1)]
    while stack:
        node, depth = stack.pop()
        deepest = max(deepest, depth)
        if isinstance(node, dict):
            stack.extend((child, depth + 1) for child in node.values())
        elif isinstance(node, list):
            stack.extend((child, depth + 1) for child in node)
    return deepest


def parse_json(text):
    """Strict JSON: NaN and Infinity are refused, and absurd nesting is a parse error, not a crash."""
    try:
        value = json.loads(text, parse_constant=reject_constant)
    except RecursionError:
        raise ValueError("nesting too deep")
    if nesting_depth(value) > MAX_NESTING:
        raise ValueError("nesting too deep")
    return value


def call_tool(data, name, arguments):
    """Runs a known tool. Returns (text, is_error)."""
    if not isinstance(arguments, dict):
        arguments = {}
    if name == "list_shared_clickys":
        return data["list_text"], False
    raw_slug = arguments.get("slug")
    slug_text = raw_slug if isinstance(raw_slug, str) else ""
    clicky = find_clicky(data, slug_text)
    if clicky is None:
        available = ", ".join(c["slug"] for c in data["clickys"])
        asked = slug_text.strip() or "(nothing)"
        return f"No shared Clicky called '{asked}'. Available ids: {available}", True
    return clicky["connector_response_text"], False


def error_response(message_id, code, text):
    return {"jsonrpc": "2.0", "id": message_id, "error": {"code": code, "message": text}}


def handle_message(data, message):
    """Returns a JSON-RPC response dict, or None when no reply is due."""
    if not isinstance(message, dict):
        return error_response(None, -32600, "Invalid request")
    method = message.get("method")
    has_id = "id" in message
    message_id = message.get("id")
    if not isinstance(method, str) or not method:
        if has_id and ("result" in message or "error" in message):
            return None  # a response from the client; nothing to answer
        return error_response(message_id if has_id else None, -32600, "Invalid request: missing method")
    if not has_id:
        return None  # notification
    if not valid_request_id(message_id):
        return error_response(None, -32600, "Invalid request: id must be a string or an integer")
    if message.get("jsonrpc") != "2.0":
        return error_response(message_id, -32600, "Invalid request: jsonrpc must be \"2.0\"")
    if "params" in message and not isinstance(message["params"], dict):
        return error_response(message_id, -32602, "Invalid params: params must be an object")
    params = message.get("params") or {}
    if method == "initialize":
        requested = params.get("protocolVersion")
        version = requested if requested in SUPPORTED_PROTOCOL_VERSIONS else SUPPORTED_PROTOCOL_VERSIONS[0]
        result = {
            "protocolVersion": version,
            "capabilities": {"tools": {"listChanged": False}},
            "serverInfo": {"name": SERVER_NAME, "version": SERVER_VERSION},
            "instructions": data["mcp"]["instructions"],
        }
    elif method == "ping":
        result = {}
    elif method == "tools/list":
        result = {"tools": data["mcp"]["tools"]}
    elif method == "tools/call":
        name = params.get("name")
        if not isinstance(name, str) or not name:
            return error_response(message_id, -32602, "Missing tool name")
        if name not in [tool["name"] for tool in data["mcp"]["tools"]]:
            return error_response(message_id, -32602, f"Unknown tool: {name}")
        if "arguments" in params and not isinstance(params["arguments"], dict):
            return error_response(message_id, -32602, "Invalid params: arguments must be an object")
        text, is_error = call_tool(data, name, params.get("arguments"))
        result = {"content": [{"type": "text", "text": text}], "isError": is_error}
    else:
        return error_response(message_id, -32601, f"Method not found: {method}")
    return {"jsonrpc": "2.0", "id": message_id, "result": result}


def batch_allowed(protocol_version):
    """JSON-RPC batching was removed in MCP 2025-06-18; older versions allow it."""
    return protocol_version != "2025-06-18"


def safe_handle(data, message):
    """Never let one bad message kill the process (HeyClicky reports a dead
    process as 'Transport closed' and does not restart it mid-turn)."""
    try:
        return handle_message(data, message)
    except Exception:
        log("handler_crash", traceback.format_exc())
        if isinstance(message, dict) and "id" not in message:
            return None
        message_id = message.get("id") if isinstance(message, dict) else None
        if not valid_request_id(message_id):
            message_id = None
        return {"jsonrpc": "2.0", "id": message_id,
                "error": {"code": -32603, "message": "Internal error"}}


def serve(input_stream, output_stream, data):
    negotiated_version = None  # set by initialize; stdio is one session per process
    for raw_line in input_stream:
        raw_line = raw_line.strip()
        if not raw_line:
            continue
        if len(raw_line.encode("utf-8", "replace")) > MAX_MESSAGE_BYTES:
            log("too_large", {"bytes": len(raw_line)})
            response = error_response(None, -32600, "Request too large")
            output_stream.write(json.dumps(response) + "\n")
            output_stream.flush()
            continue
        try:
            message = parse_json(raw_line)
        except ValueError:
            log("bad_json", raw_line[:500])
            response = {"jsonrpc": "2.0", "id": None,
                        "error": {"code": -32700, "message": "Parse error"}}
        else:
            log("in", message)
            if isinstance(message, list):  # JSON-RPC batch (allowed before 2025-06-18)
                if not message:
                    response = error_response(None, -32600, "Empty batch")
                elif not batch_allowed(negotiated_version):
                    response = error_response(None, -32600, "Batching is not supported in protocol 2025-06-18")
                else:
                    replies = [r for r in (safe_handle(data, m) for m in message) if r is not None]
                    response = replies or None
            else:
                response = safe_handle(data, message)
                if (isinstance(message, dict) and message.get("method") == "initialize"
                        and isinstance(response, dict) and "result" in response):
                    negotiated_version = response["result"]["protocolVersion"]
        if response is not None:
            try:
                output_stream.write(json.dumps(response, allow_nan=False) + "\n")
                output_stream.flush()
            except (BrokenPipeError, OSError) as error:
                log("write_failed", repr(error))
                return
            log("out", response)
    log("stdin_closed", {})


def on_terminate(signal_number, _frame):
    log("signal", {"signal": signal_number})
    sys.exit(0)


def main():
    for stream in (sys.stdin, sys.stdout):
        try:
            stream.reconfigure(encoding="utf-8", errors="replace")
        except (AttributeError, ValueError):
            pass
    for signal_name in ("SIGTERM", "SIGHUP"):
        if hasattr(signal, signal_name):
            signal.signal(getattr(signal, signal_name), on_terminate)
    atexit.register(lambda: log("exit", {}))
    try:
        data = load_data()
    except (OSError, ValueError) as error:
        sys.stderr.write(f"share-a-clicky: cannot read {DATA_PATH}: {error}\n")
        log("startup_failed", repr(error))
        return 1
    log("start", {"python": sys.version.split()[0], "clickys": len(data["clickys"]),
                  "cwd": os.getcwd(), "parent_pid": os.getppid()})
    serve(sys.stdin, sys.stdout, data)
    return 0


if __name__ == "__main__":
    sys.exit(main())
